quiz1:
	g++ quiz1.cpp
	./a.out
	rm a.out

quiz2:
	g++ quiz2.cpp
	./a.out
	rm a.out

quiz3:
	g++ quiz3.cpp
	./a.out
	rm a.out

quiz4:
	g++ quiz4.cpp
	./a.out
	rm a.out

quiz6:
	g++ quiz6.cpp
	./a.out
	rm a.out