arrays:
	g++ ed20cr_arrays.cpp -o arrays
	./arrays
	rm arrays

matrix:
	g++ ed20cr_matrix.cpp -o matrix
	./matrix
	rm matrix

matrixTest1:
	g++ ed20cr_matrix.cpp -o matrix
	./matrix < testfile.txt
	rm matrix