stringops:
	g++ ed20cr_stringops.cpp -o stringops
	./stringops
	rm stringops

wordreverse:
	g++ ed20cr_wordReverse.cpp -o wordreverse
	./wordreverse < wordReverseTest.txt
	rm wordreverse

mirror:
	g++ ed20cr_mirroredStrings.cpp -o mirroredStrings
	./mirroredStrings
	rm mirroredStrings