main:
	g++ helloworld.cpp -o blahblah

blah:
	g++ helloworld.cpp -o blahblah
	./blahblah
	
milestone1:
	g++ milestone1.cpp -o milestone1
	./milestone1
	rm milestone1

rockpaperscissors:
	g++ rockpaperscissors.cpp -o rockpaperscissors
	./rockpaperscissors
	rm rockpaperscissors

milestone2:
	g++ milestone2.cpp -o milestone2
	./milestone2 < testfile.txt
	rm milestone2

milestone3:
	g++ milestone3.cpp -o milestone3
	./milestone3
	rm milestone3