flipsum:
	g++ ed20cr_flipsum.cpp -o flipsum
	./flipsum
	rm flipsum

probability:
	g++ ed20cr_probability.cpp -o probability
	./probability
	rm probability 

probability1:
	g++ ed20cr_probability.cpp -o probability
	./probability < test.txt
	rm probability