numbers:
	g++ ed20cr_numbers.cpp -o numbers
	./numbers
	rm numbers

ntest1:
	g++ ed20cr_numbers.cpp -o numbers
	./numbers < input1.txt
	rm numbers

ntest2:
	g++ ed20cr_numbers.cpp -o numbers
	./numbers < input2.txt
	rm numbers

distance:
	g++ ed20cr_distance.cpp -o distance
	./distance
	rm distance